---
title: "TCGA_CellTFusion"
output: html_document
date: "2024-08-05"
---

Load data
```{r}
load("~/Documents/CellTFusion/user_projects/counts_early_TCGA.RData")
set.seed(123)
source("src/environment_set.R") #Load functions and packages
```

Preprocessing genes (keep only coding genes)
```{r}
library(biomaRt)
library(stringr)
rownames(counts.norm) <- str_replace(rownames(counts.norm),
                        pattern = ".[0-9]+$",
                        replacement = "")

gene_ids <- rownames(counts.norm)

mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Get gene type annotations
annotations <- getBM(attributes = c("ensembl_gene_id", "gene_biotype"), 
                     filters = "ensembl_gene_id", 
                     values = gene_ids, 
                     mart = mart)

# Filter annotations to keep only coding genes
coding_genes <- annotations %>%
  filter(gene_biotype == "protein_coding") %>%
  pull(ensembl_gene_id)

counts.norm = counts.norm[coding_genes,]

entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = rownames(counts.norm), columns = "SYMBOL", keytype = "ENSEMBL") %>%
  distinct(SYMBOL, .keep_all=T) %>% 
  group_by(ENSEMBL) %>%
  slice(1) %>%
  ungroup() %>%
  na.omit()

counts.norm = counts.norm[entrz$ENSEMBL,] %>%
  data.frame() %>%
  mutate(Symbol = entrz$SYMBOL) %>%
  remove_rownames() %>%
  column_to_rownames("Symbol") 

# Get gene type annotations
annotations_symbol <- getBM(attributes = c("hgnc_symbol", "gene_biotype"),
                     filters = "hgnc_symbol",
                     values = rownames(counts.norm),
                     mart = mart)

# Filter annotations to keep only coding genes
coding_genes <- annotations_symbol %>%
  filter(gene_biotype == "protein_coding") %>%
  pull(hgnc_symbol)

counts.norm = counts.norm[rownames(counts.norm) %in% coding_genes,]
```

Perform deconvolution and TFs inference
```{r}
counts.normalized = ADImpute::NormalizeTPM(counts.norm, log=T) 
deconv = compute.deconvolution(counts.normalized, normalized = F, credentials.mail = "marcelo.hurtado@inserm.fr", credentials.token = "734212f6ad77fc4eea2bdb502792f294")
tfs = compute.TFs.activity(counts.normalized)
```

Rename variables
```{r}
counts.tcga = counts.norm
counts.norm.tcga = counts.normalized
deconv.tcga = deconv
tfs.tcga = tfs
traitData.tcga = traitData
```

Compute cell signatures from LP in TCGA
```{r}
load("~/Documents/CellTFusion/user_projects/LP_early_results.RData") 
tcga_groups = compute_cell_groups_signatures(dt, network, res_all, features = cell_groups_selected$Confirmed, deconv.tcga, tfs.tcga)
```

Immunescores
```{r}
gold.standards <- compute_gold_standards(RNA.tpm = data.frame(counts.norm.tcga))
```

TCGA trait data
```{r}
traitData.tcga = traitData.tcga %>%
  mutate(Stages_simplified = case_when(Stages_simplified == "Stage I" ~ "I",
                                        TRUE ~ 'II'))

```

Heatmap of TCGA cell groups
```{r}
hc_tcga = hclust(dist(tcga_groups), method = "ward.D2")
dend_column = as.dendrogram(hc_tcga)

annotations = cbind(traitData.tcga, gold.standards)

ha = heatmap_annotation(annotations)

ht1 = Heatmap(t(scale(tcga_groups)), 
        border = T, cluster_columns = dend_column, cluster_rows = dend_row,
        top_annotation = ha, column_gap = unit(8, "mm"), 
        name = "Cell groups", clustering_method_rows = "ward.D2", clustering_method_columns = "ward.D2",
        column_dend_height = unit(5, "cm"), row_dend_width = unit(5, "cm"), 
        column_dend_reorder = T, row_dend_reorder = F,
        show_row_names = T, 
        show_heatmap_legend = T, 
        row_names_gp = gpar(fontsize = 16), 
        column_names_gp = gpar(fontsize =12), 
        width = unit(30, "cm"), height = unit(10, "cm"),
        heatmap_legend_param = list(labels_gp = gpar(fontsize = 12), legend_width = unit(12, "cm"), 
                                    legend_heigh = unit(12, "cm"), title_gp = gpar(fontsize = 12)))

pdf("Results/Heatmap_cells_groups_boruta_TCGA", width = 35, height = 15)
draw(ht1, show_heatmap_legend = T, heatmap_legend_side = "left", annotation_legend_side = 'left')
dev.off()
```

Patient classification
```{r}
library(factoextra)
traitData.tcga = traitData.tcga %>%
  mutate(Cluster = cutree(dend_column, k = 3))

pdf("Results/Dendrogram_samples", width = 14, height = 8)
par(mar = c(5, 1, 1, 1)) #bottom, left, top, right
plot(dend_column, cex = 0.6)
dendextend::rect.dendrogram(dend_column, k=3, border = 2:5)
dev.off()
```

Differential expression analysis
```{r}
rownames(traitData.tcga) = str_replace_all(rownames(traitData.tcga), "-", ".")
traitData.tcga$Cluster = factor(traitData.tcga$Cluster)
deseq2Data <- DESeqDataSetFromMatrix(countData=round(counts.tcga), colData=traitData.tcga, design= ~ Cluster)
deseq2Data <- deseq2Data[rowSums(counts(deseq2Data)) > 5, ]
deseq2Data <- DESeq(deseq2Data)
resultsNames(deseq2Data)
deseq2Results <- results(deseq2Data, contrast = c("Cluster", "3", "1"))
deseq2Results = data.frame(deseq2Results)
sigGenes <- rownames(deseq2Results[which(deseq2Results$padj <= .00001 & abs(deseq2Results$log2FoldChange) > 1.5),])

library(EnhancedVolcano)
pdf("Results/DEG_Volcano_TCGA", width = 10, height = 8)
EnhancedVolcano(deseq2Results, lab = rownames(deseq2Results), x = 'log2FoldChange', y = 'padj')
dev.off()
```

Enrichment analysis
```{r}
entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = sigGenes, columns = "ENTREZID", keytype = "SYMBOL") #Change to EntrezID

kk <- enrichKEGG(gene         = entrz$ENTREZID,
                 organism     = 'hsa',
                 pvalueCutoff = 0.05)

pdf("Results/Enrichment_result_TCGA_dotplot", width = 6, height = 12)
dotplot(kk, showCategory=35) + ggtitle("ORA - KEGG pathways")
dev.off()
```

Survival analysis
```{r}
colnames(traitData.tcga)[c(7,8)] = c("DRP_st","PFS")
survival.data = traitData.tcga[,c(7,8)] #Keep only survival information
survival.data = na.omit(survival.data) #Remove samples with NA
tcga_groups = tcga_groups[rownames(survival.data),]
survival_groups = compute.survival.analysis(features = tcga_groups, survival.data, time_unit = "days", p.value = 0.01, max_factors = 1, thres = 0.66)
```

